# Generated by Django 3.2.5 on 2022-06-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptoms', models.CharField(max_length=200, null=True)),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('aadharnum', models.PositiveIntegerField(max_length=16, null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('specilization', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('interval', models.PositiveIntegerField(null=True)),
                ('Dosage', models.PositiveIntegerField(null=True)),
                ('Appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.appointments')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('aadharnum', models.PositiveIntegerField(max_length=16, null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.PositiveBigIntegerField(null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('available', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diagonosis', models.CharField(max_length=200, null=True)),
                ('Remarks', models.CharField(max_length=200, null=True)),
                ('Appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.appointments')),
                ('Medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medicines')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='Slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.slots'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctor'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient'),
        ),
    ]
