# Generated by Django 3.2.5 on 2022-06-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.PositiveSmallIntegerField(default=145),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.PositiveSmallIntegerField(default=45),
        ),
    ]
